version: '3'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SQL_SERVER_PWD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data 
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets